In [3]:
import numpy as np
import pandas as pd

In [4]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv') 

In [5]:
df_train.head()

Survived        Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  28.500000   7.2292         0         0         1           0   
1         1  27.000000  10.5000         0         1         0           1   
2         1  29.699118  16.1000         0         0         1           1   
3         0  29.699118   0.0000         1         0         0           0   
4         0  17.000000   8.6625         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        1        0  ...        1        0        0        0   
1         0        1        0  ...        1        0        0        0   
2         0        0        1  ...        1        0        0        0   
3         1        1        0  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           1           0           0  
1        0        0        0           0           0           1  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

In [6]:
print("Training Data Shape: ",df_train.shape)
print("Test Data Shape :",df_test.shape)

Training Data Shape:  (712, 25)
Test Data Shape : (179, 25)


In [7]:
train_x = df_train.drop(columns =['Survived'],axis =1)
train_y = df_train['Survived']

In [8]:
test_x = df_test.drop(columns =['Survived'],axis =1)
test_y = df_test['Survived']

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
lr = LogisticRegression()

In [11]:
lr.fit(train_x,train_y)

C:\Users\Flash\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
preds_y = lr.predict(test_x)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix,roc_curve,roc_auc_score

In [14]:
accuracy_score(test_y,preds_y)

0.8212290502793296

In [15]:
confusion_matrix(test_y,preds_y)

array([[101,  16],
       [ 16,  46]], dtype=int64)

In [17]:
roc_curve(test_y,preds_y)

(array([0.        , 0.13675214, 1.        ]),
 array([0.        , 0.74193548, 1.        ]),
 array([2, 1, 0], dtype=int64))

In [18]:
print('Coefficient of model :', lr.coef_)

Coefficient of model : [[-0.0309277   0.0015481   0.89622702  0.06137478 -1.00592965  1.25419984
  -1.30252768  1.05848089  0.98967108  0.74258032 -1.03750838 -0.76764093
  -0.42457927 -0.60933156  0.31409761  0.69532881  0.09004334  0.30114508
  -0.69551091 -0.44316213 -0.31026964  0.16940127  0.1551816  -0.37291072]]


In [19]:
print('Intercept of model',lr.intercept_)

Intercept of model [-0.04832785]


In [20]:
print("Auc Score :",roc_auc_score(test_y,preds_y))

Auc Score : 0.8025916735594155


## Save Model

In [21]:
import pickle

In [27]:
filename = 'Logistic_model.sav'
pickle.dump(lr, open(filename, 'wb'))