In [1]:
import numpy as np
import pandas as pd

In [2]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv') 

In [3]:
df_train.head()

Survived        Age     Fare  Pclass_1  Pclass_2  Pclass_3  Sex_female  \
0         0  28.500000   7.2292         0         0         1           0   
1         1  27.000000  10.5000         0         1         0           1   
2         1  29.699118  16.1000         0         0         1           1   
3         0  29.699118   0.0000         1         0         0           0   
4         0  17.000000   8.6625         0         0         1           0   

   Sex_male  SibSp_0  SibSp_1  ...  Parch_0  Parch_1  Parch_2  Parch_3  \
0         1        1        0  ...        1        0        0        0   
1         0        1        0  ...        1        0        0        0   
2         0        0        1  ...        1        0        0        0   
3         1        1        0  ...        1        0        0        0   
4         1        1        0  ...        1        0        0        0   

   Parch_4  Parch_5  Parch_6  Embarked_C  Embarked_Q  Embarked_S  
0        0        0        0           1           0           0  
1        0        0        0           0           0           1  
2        0        0        0           0           0           1  
3        0        0        0           0           0           1  
4        0        0        0           0           0           1  

[5 rows x 25 columns]

In [4]:
print("Training Data Shape: ",df_train.shape)
print("Test Data Shape :",df_test.shape)

Training Data Shape:  (712, 25)
Test Data Shape : (179, 25)


In [5]:
train_x = df_train.drop(columns =['Survived'],axis =1)
train_y = df_train['Survived']

In [6]:
test_x = df_test.drop(columns =['Survived'],axis =1)
test_y = df_test['Survived']

In [7]:
from sklearn.neighbors import KNeighborsClassifier as knn

In [8]:
lr  = knn()

In [9]:
lr.fit(train_x,train_y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [10]:
preds_y = lr.predict(test_x)

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix,roc_curve,roc_auc_score

In [12]:
print("Accuracy:" ,accuracy_score(test_y,preds_y)*100//1,"%")

Accuracy: 71.0 %


In [13]:
confusion_matrix(test_y,preds_y)

array([[95, 22],
       [29, 33]], dtype=int64)

In [14]:
roc_curve(test_y,preds_y)

(array([0.        , 0.18803419, 1.        ]),
 array([0.        , 0.53225806, 1.        ]),
 array([2, 1, 0], dtype=int64))

In [15]:
print("Auc Score :",roc_auc_score(test_y,preds_y))

Auc Score : 0.6721119382409705


## Save Model

In [16]:
import pickle

In [17]:
filename = 'k- Nearest Neighbors.sav'
pickle.dump(lr, open(filename, 'wb'))